version: '3.7'

services:
  php7:
    container_name: php7
    build: ./php
    volumes:
      - "../config/php:/usr/local/etc/php"
      - "../code/myapp:/var/www/html/myapp"
    depends_on:
      - mariadb
    networks:
      - lemp-network

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8080:80
    volumes:
      - "../config/nginx:/etc/nginx/conf.d"
      - "../code/myapp:/var/www/html/myapp"
      - "../logs:/var/log/nginx"
    depends_on:
      - php7
    networks:
      - lemp-network

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    volumes:
      - "../mariadb/data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=docker_sample
    ports:
      - 3306:3306
    networks:
      - lemp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mariadb
    ports:
      - 8081:80
    networks:
      - lemp-network

networks:
  lemp-network:
    driver: bridge